CREATE OR REPLACE PROCEDURE VEHICULO_CRUD(
	OPCION VARCHAR2,
	COD_VEHICULO_P INT DEFAULT NULL,
    MARCA_VEHICULO_P VARCHAR2 DEFAULT NULL,
	PATENTE_P VARCHAR2 DEFAULT NULL,
    MENSAJE OUT VARCHAR2
)
IS
BEGIN
	LOCK TABLE VEHICULO IN ROW EXCLUSIVE MODE;

	IF (OPCION = 'R') THEN
		INSERT INTO VEHICULO(COD_VEHICULO,MARCA_VEHICULO,PATENTE)
			VALUES(COD_VEHICULO_P,MARCA_VEHICULO_P,PATENTE_P);
        MENSAJE := 'vehiculo insertado correctamente';
	END IF;

	IF (OPCION = 'U') THEN
		UPDATE VEHICULO SET
            COD_VEHICULO = COD_VEHICULO_P,
			MARCA_VEHICULO = MARCA_VEHICULO_P,
			PATENTE = PATENTE_P,

			WHERE(COD_VEHICULO = COD_VEHICULO_P);
        MENSAJE := 'vehiculo actualizado correctamente';
	END IF;

	IF (OPCION = 'D') THEN
		DELETE FROM VEHICULO WHERE(COD_VEHICULO = COD_VEHICULO_P);
        MENSAJE := 'vehiculo eliminado correctamente';
	END IF;
	COMMIT;
	EXCEPTION
		WHEN DUP_VAL_ON_INDEX THEN
			RAISE_APPLICATION_ERROR(-20001,'CÓDIGO REPETIDO');
		WHEN OTHERS THEN
			RAISE_APPLICATION_ERROR(-20010,'OCURRIÓ UN ERROR');
		ROLLBACK;
END;

----------------------------------------

CREATE OR REPLACE PROCEDURE USUARIO_CRUD(
	OPCION VARCHAR2,
	RUT_P INT DEFAULT NULL,
	CONTRASEÑA_P DEFAULT NULL,
    NOMBRE_USUARIO_P INT DEFAULT NULL,
	APELLIDO_USUARIO_P NUMBER DEFAULT NULL,
	COD_ROL_P INT DEFAULT NULL,
    MENSAJE OUT VARCHAR2
)
IS
BEGIN
	LOCK TABLE USUARIO IN ROW EXCLUSIVE MODE;

	IF (OPCION = 'R') THEN
		INSERT INTO USUARIO(RUT,CONTRASEÑA,NOMBRE_USUARIO,APELLIDO_USUARIO,COD_ROL)
			VALUES(RUT_P,CONTRASEÑA_P,NOMBRE_USUARIO_P,APELLIDO_USUARIO_P,COD_ROL_P);
        MENSAJE := 'usuario insertado correctamente';
	END IF;

	IF (OPCION = 'U') THEN
		UPDATE USUARIO SET
            RUT = RUT_P,
            CONTRASEÑA = CONTRASEÑA_P
			NOMBRE_USUARIO = NOMBRE_USUARIO_P,
			APELLIDO_USUARIO = APELLIDO_USUARIO_P,
			COD_ROL = COD_ROL_P,

			WHERE(COD_USUARIO = COD_USUARIO_P);
        MENSAJE := 'usuario actualizado correctamente';
	END IF;

	IF (OPCION = 'D') THEN
		DELETE FROM USUARIO WHERE(RUT = RUT_P);
        MENSAJE := 'usuario eliminado correctamente';
	END IF;
	COMMIT;
	EXCEPTION
		WHEN DUP_VAL_ON_INDEX THEN
			RAISE_APPLICATION_ERROR(-20001,'CÓDIGO REPETIDO');
		WHEN OTHERS THEN
			RAISE_APPLICATION_ERROR(-20010,'OCURRIÓ UN ERROR');
		ROLLBACK;
END;

----------------------------------------

CREATE OR REPLACE PROCEDURE DETALLE_USUARIO_VEHICULO_CRUD(
	OPCION VARCHAR2,
	COD_USUARIO_VEHICULO_P INT DEFAULT NULL,
    COD_USUARIO_P INT DEFAULT NULL,
    COD_VEHICULO_P INT DEFAULT NULL,
    MENSAJE OUT VARCHAR2
)
IS
BEGIN
	LOCK TABLE DETALLE_USUARIO_VEHICULO IN ROW EXCLUSIVE MODE;

	IF (OPCION = 'R') THEN
		INSERT INTO DETALLE_USUARIO_VEHICULO(COD_USUARIO_VEHICULO,COD_USUARIO,COD_VEHICULO)
			VALUES(COD_USUARIO_VEHICULO_P,COD_USUARIO_P,COD_VEHICULO_P);
        MENSAJE := 'detalle insertado correctamente';
	END IF;

	IF (OPCION = 'U') THEN
		UPDATE DETALLE_USUARIO_VEHICULO SET
            COD_USUARIO_VEHICULO = COD_USUARIO_VEHICULO_P,
			COD_USUARIO = COD_USUARIO_P,
			COD_VEHICULO = COD_VEHICULO_P,

			WHERE(COD_USUARIO_VEHICULO = COD_USUARIO_VEHICULO_P);
        MENSAJE := 'detalle actualizado correctamente';
	END IF;

	IF (OPCION = 'D') THEN
		DELETE FROM DETALLE_USUARIO_VEHICULO WHERE(COD_USUARIO_VEHICULO = COD_USUARIO_VEHICULO_P);
        MENSAJE := 'detalle eliminado correctamente';
	END IF;
	COMMIT;
	EXCEPTION
		WHEN DUP_VAL_ON_INDEX THEN
			RAISE_APPLICATION_ERROR(-20001,'CÓDIGO REPETIDO');
		WHEN OTHERS THEN
			RAISE_APPLICATION_ERROR(-20010,'OCURRIÓ UN ERROR');
		ROLLBACK;
END;

----------------------------------------


CREATE OR REPLACE PROCEDURE PRODUCTO_CRUD(
	OPCION VARCHAR2,
	COD_PRODUCTO_P INT DEFAULT NULL,
    NOMBRE_PRODUCTO_P VARCHAR2 DEFAULT NULL,
    PRECIO_P INT DEFAULT NULL,
    MENSAJE OUT VARCHAR2
)
IS
BEGIN
	LOCK TABLE PRODUCTO IN ROW EXCLUSIVE MODE;

	IF (OPCION = 'R') THEN
		INSERT INTO PRODUCTO(COD_PRODUCTO,NOMBRE_PRODUCTO,PRECIO)
			VALUES(COD_PRODUCTO_P,NOMBRE_PRODUCTO_P,PRECIO_P);
        MENSAJE := 'producto insertado correctamente';
	END IF;

	IF (OPCION = 'U') THEN
		UPDATE PRODUCTO SET
            COD_PRODUCTO = COD_PRODUCTO_P,
			NOMBRE_PRODUCTO = NOMBRE_PRODUCTO_P,
			PRECIO = PRECIO_P

			WHERE(COD_PRODUCTO = COD_PRODUCTO_P);
        MENSAJE := 'producto actualizado correctamente';
	END IF;

	IF (OPCION = 'D') THEN
		DELETE FROM PRODUCTO WHERE(COD_PRODUCTO = COD_PRODUCTO_P);
        MENSAJE := 'producto eliminado correctamente';
	END IF;
	COMMIT;
	EXCEPTION
		WHEN DUP_VAL_ON_INDEX THEN
			RAISE_APPLICATION_ERROR(-20001,'CÓDIGO REPETIDO');
		WHEN OTHERS THEN
			RAISE_APPLICATION_ERROR(-20010,'OCURRIÓ UN ERROR');
		ROLLBACK;
END;
----------------------------------------

CREATE OR REPLACE PROCEDURE SUCURSAL_CRUD(
	OPCION VARCHAR2,
	COD_SUCURSAL_P INT DEFAULT NULL,
    NOMBRE_SUCURSAL_P VARCHAR2 DEFAULT NULL,
    COD_CIUDAD_SUCURSAL_P INT DEFAULT NULL,
    CALLE_SUCURSAL_P VARCHAR2 DEFAULT NULL,
    NRO_DIRECCION_SUCURSAL_P INT DEFAULT NULL,
    MENSAJE OUT VARCHAR2
)
IS
BEGIN
	LOCK TABLE SUCURSAL IN ROW EXCLUSIVE MODE;

	IF (OPCION = 'R') THEN
		INSERT INTO SUCURSAL(COD_SUCURSAL,NOMBRE_SUCURSAL,COD_CIUDAD_SUCURSAL,CALLE_SUCURSAL,NRO_DIRECCION_SUCURSAL)
			VALUES(COD_SUCURSAL_P,NOMBRE_SUCURSAL_P,COD_CIUDAD_SUCURSAL_P,CALLE_SUCURSAL_P,NRO_DIRECCION_SUCURSAL_P);
        MENSAJE := 'sucursal insertada correctamente';
	END IF;

	IF (OPCION = 'U') THEN
		UPDATE SUCURSAL SET
            COD_SUCURSAL = COD_SUCURSAL_P,
			NOMBRE_SUCURSAL = NOMBRE_SUCURSAL_P,
			COD_CIUDAD_SUCURSAL = COD_CIUDAD_SUCURSAL_P,
			CALLE_SUCURSAL = CALLE_SUCURSAL_P,
			NRO_DIRECCION_SUCURSAL = NRO_DIRECCION_SUCURSAL_P,

			WHERE(COD_SUCURSAL = COD_SUCURSAL_P);
        MENSAJE := 'sucursal actualizada correctamente';
	END IF;

	IF (OPCION = 'D') THEN
		DELETE FROM SUCURSAL WHERE(COD_SUCURSAL = COD_SUCURSAL_P);
        MENSAJE := 'sucursal eliminada correctamente';
	END IF;
	COMMIT;
	EXCEPTION
		WHEN DUP_VAL_ON_INDEX THEN
			RAISE_APPLICATION_ERROR(-20001,'CÓDIGO REPETIDO');
		WHEN OTHERS THEN
			RAISE_APPLICATION_ERROR(-20010,'OCURRIÓ UN ERROR');
		ROLLBACK;
END;
----------------------------------------

CREATE OR REPLACE PROCEDURE INVENTARIO_CRUD(
	OPCION VARCHAR2,
	COD_INVENTARIO_P INT DEFAULT NULL,
    COD_PRODUCTO_P INT DEFAULT NULL,
    COD_SUCURSAL_P INT DEFAULT NULL,
    CANTIDAD_TOTAL_P INT DEFAULT NULL,
    CANTIDAD_DISPONIBLE_P DEFAULT NULL,
    MENSAJE OUT VARCHAR2
)
IS
BEGIN
	LOCK TABLE INVENTARIO IN ROW EXCLUSIVE MODE;

	IF (OPCION = 'R') THEN
		INSERT INTO INVENTARIO(COD_INVENTARIO,COD_PRODUCTO,COD_SUCURSAL,CANTIDAD_TOTAL,CANTIDAD_DISPONIBLE)
			VALUES(COD_INVENTARIO_P,COD_PRODUCTO_P,COD_SUCURSAL_P,CANTIDAD_TOTAL_P,CANTIDAD_DISPONIBLE_P);
        MENSAJE := 'producto insertado correctamente';
	END IF;

	IF (OPCION = 'U') THEN
		UPDATE INVENTARIO SET
            COD_INVENTARIO = COD_INVENTARIO_P,
			COD_PRODUCTO = COD_PRODUCTO_P,
			COD_SUCURSAL = COD_SUCURSAL_P,
			CANTIDAD_TOTAL = CANTIDAD_TOTAL_P,
			CANTIDAD_DISPONIBLE = CANTIDAD_DISPONIBLE_P,

			WHERE(COD_INVENTARIO = COD_INVENTARIO_P);
        MENSAJE := 'producto actualizado correctamente';
	END IF;

	IF (OPCION = 'D') THEN
		DELETE FROM INVENTARIO WHERE(COD_INVENTARIO = COD_INVENTARIO_P);
        MENSAJE := 'producto eliminado correctamente';
	END IF;
	COMMIT;
	EXCEPTION
		WHEN DUP_VAL_ON_INDEX THEN
			RAISE_APPLICATION_ERROR(-20001,'CÓDIGO REPETIDO');
		WHEN OTHERS THEN
			RAISE_APPLICATION_ERROR(-20010,'OCURRIÓ UN ERROR');
		ROLLBACK;
END;

----------------------------------------

CREATE OR REPLACE PROCEDURE PEDIDO_CRUD(
	OPCION VARCHAR2,
	COD_PEDIDO_P INT DEFAULT NULL,
    COD_PRODUCTO_P INT DEFAULT NULL,
    CANTIDAD_SOLICITADA_P INT DEFAULT NULL,
    MENSAJE OUT VARCHAR2
)
IS
BEGIN
	LOCK TABLE PEDIDO IN ROW EXCLUSIVE MODE;

	IF (OPCION = 'R') THEN
		INSERT INTO PEDIDO(COD_PEDIDO,COD_PRODUCTO,COD_STOCK,CANTIDAD_SOLICITADA)
			VALUES(COD_PEDIDO_P,COD_PRODUCTO_P,CANTIDAD_SOLICITADA_P);
        MENSAJE := 'pedido insertada correctamente';
	END IF;

	IF (OPCION = 'U') THEN
		UPDATE PEDIDO SET
            COD_PEDIDO = COD_PEDIDO_P,
			COD_PRODUCTO = COD_PRODUCTO_P,
			CANTIDAD_SOLICITADA = CANTIDAD_SOLICITADA_P,

			WHERE(COD_PEDIDO = COD_PEDIDO_P);
        MENSAJE := 'pedido actualizado correctamente';
	END IF;

	IF (OPCION = 'D') THEN
		DELETE FROM PEDIDO WHERE(COD_PEDIDO = COD_PEDIDO_P);
        MENSAJE := 'pedido eliminado correctamente';
	END IF;
	COMMIT;
	EXCEPTION
		WHEN DUP_VAL_ON_INDEX THEN
			RAISE_APPLICATION_ERROR(-20001,'CÓDIGO REPETIDO');
		WHEN OTHERS THEN
			RAISE_APPLICATION_ERROR(-20010,'OCURRIÓ UN ERROR');
		ROLLBACK;
END;
----------------------------------------

CREATE OR REPLACE PROCEDURE RESERVA_CRUD(
	OPCION VARCHAR2,
	COD_RESERVA_P INT DEFAULT NULL,
	CELULAR_CLIENTE_P INT DEFAULT NULL,
    COD_PEDIDO_P INT DEFAULT NULL,
    COD_DISP_P INT DEFAULT NULL,
    COD_VEHICULO_P INT DEFAULT NULL,
    ESTADO_P INT DEFAULT NULL,
    TOTAL_P INT DEFAULT NULL,
    MENSAJE OUT VARCHAR2
)
IS
BEGIN
	LOCK TABLE RESERVA IN ROW EXCLUSIVE MODE;

	IF (OPCION = 'R') THEN
		INSERT INTO RESERVA(COD_RESERVA,CELULAR_CLIENTE,COD_PEDIDO,COD_DISP,COD_VEHICULO,ESTADO,TOTAL)
			VALUES(COD_RESERVA_P,CELULAR_CLIENTE_P,COD_PEDIDO_P,COD_DISP_P,COD_VEHICULO_P,ESTADO_P,TOTAL_P);
        MENSAJE := 'reserva insertada correctamente';
	END IF;

	IF (OPCION = 'U') THEN
		UPDATE RESERVA SET
            COD_RESERVA = COD_RESERVA_P,
			CELULAR_CLIENTE = CELULAR_CLIENTE_P,
			COD_PEDIDO = COD_PEDIDO_P,
			COD_DISP = COD_DISP_P,
			COD_VEHICULO = COD_VEHICULO_P,
			ESTADO = ESTADO_P,
			TOTAL = TOTAL_P,

			WHERE(COD_RESERVA = COD_RESERVA_P);
        MENSAJE := 'reserva actualizada correctamente';
	END IF;

	IF (OPCION = 'D') THEN
		DELETE FROM RESERVA WHERE(COD_RESERVA = COD_RESERVA_P);
        MENSAJE := 'reserva eliminada correctamente';
	END IF;
	COMMIT;
	EXCEPTION
		WHEN DUP_VAL_ON_INDEX THEN
			RAISE_APPLICATION_ERROR(-20001,'CÓDIGO REPETIDO');
		WHEN OTHERS THEN
			RAISE_APPLICATION_ERROR(-20010,'OCURRIÓ UN ERROR');
		ROLLBACK;
END;

----------------------------------------

CREATE OR REPLACE PROCEDURE CLIENTE_CRUD(
	OPCION VARCHAR2,
	CELULAR_CLIENTE_P INT DEFAULT NULL,
    NOMBRE_CLIENTE_P VARCHAR2 DEFAULT NULL,
    APELLIDO_CLIENTE_P VARCHAR2 DEFAULT NULL,
    DIRECCION_CLIENTE_P VARCHAR2 DEFAULT NULL,
    MENSAJE OUT VARCHAR2
)
IS
BEGIN
	LOCK TABLE CLIENTE IN ROW EXCLUSIVE MODE;

	IF (OPCION = 'R') THEN
		INSERT INTO CLIENTE(CELULAR_CLIENTE,NOMBRE_CLIENTE,APELLIDO_CLIENTE,DIRECCION_CLIENTE)
			VALUES(CELULAR_CLIENTE_P,NOMBRE_CLIENTE_P,APELLIDO_CLIENTE_P,DIRECCION_CLIENTE_P);
        MENSAJE := 'cliente insertado correctamente';
	END IF;

	IF (OPCION = 'U') THEN
		UPDATE RESERVA SET
			CELULAR_CLIENTE = CELULAR_CLIENTE_P,
			NOMBRE_CLIENTE = NOMBRE_CLIENTE_P,
			APELLIDO_CLIENTE_P = APELLIDO_CLIENTE_P,
			DIRECCION_CLIENTE = DIRECCION_CLIENTE_P,

			WHERE(CELULAR_CLIENTE = CELULAR_CLIENTE_P);
        MENSAJE := 'cliente actualizado correctamente';
	END IF;

	IF (OPCION = 'D') THEN
		DELETE FROM CLIENTE WHERE(CELULAR_CLIENTE = CELULAR_CLIENTE_P);
        MENSAJE := 'cliente eliminado correctamente';
	END IF;
	COMMIT;
	EXCEPTION
		WHEN DUP_VAL_ON_INDEX THEN
			RAISE_APPLICATION_ERROR(-20001,'CÓDIGO REPETIDO');
		WHEN OTHERS THEN
			RAISE_APPLICATION_ERROR(-20010,'OCURRIÓ UN ERROR');
		ROLLBACK;
END;

