CREATE TABLE VEHICULO (
    COD_VEHICULO INT,
    MARCA_VEHICULO VARCHAR(30),
    PATENTE VARCHAR(10),
    PRIMARY KEY(COD_VEHICULO)

);

CREATE TABLE ROL_USUARIO (
    COD_ROL INT,
    NOMBRE_ROL VARCHAR(30),
    PRIMARY KEY(COD_ROL)
);

CREATE TABLE USUARIO (
    RUT_USUARIO VARCHAR(10),
    CONTRASEÑA VARCHAR(30),
    NOMBRE_USUARIO VARCHAR(30),
    APELLIDO_USUARIO VARCHAR(30),
    COD_ROL INT,
    PRIMARY KEY(RUT_USUARIO)
);

CREATE TABLE DETALLE_USUARIO_VEHICULO (
    COD_USUARIO_VEHICULO INT,
    RUT_USUARIO VARCHAR(10),
    COD_VEHICULO INT,
    PRIMARY KEY(COD_USUARIO_VEHICULO),
    CONSTRAINT FOREIGN KEY (RUT_USUARIO) REFERENCES USUARIO(RUT_USUARIO),
    CONSTRAINT FOREIGN KEY (COD_VEHICULO) REFERENCES VEHICULO(COD_VEHICULO)
);

CREATE TABLE DISPONIBILIDAD_FECHA(
    COD_DISPONIBILIDAD_FECHA INT,
    FECHA_ENTREGA DATE,
    HORARIO_ENTREGA TIME,
    PRIMARY KEY (COD_DISPONIBILIDAD_FECHA)
);

CREATE TABLE CLIENTE(
    CELULAR_CLIENTE INT,
    NOMBRE_CLIENTE VARCHAR(30),
    APELLIDO_CLIENTE VARCHAR(30),
    DIRECCION_CLIENTE VARCHAR(60),
    PRIMARY KEY(CELULAR_CLIENTE)
);

CREATE TABLE PRODUCTO(
    COD_PRODUCTO INT,
    NOMBRE_PRODUCTO VARCHAR(30),
    PRECIO_PRODUCTO INT,
    PRIMARY KEY(COD_PRODUCTO)
);

CREATE TABLE CIUDAD_SUCURSAL(
    COD_CIUDAD_SUCURSAL INT,
    NOMBRE_CIUDAD VARCHAR(50),
    PRIMARY KEY(COD_CIUDAD_SUCURSAL)
);
CREATE TABLE SUCURSAL(
    COD_SUCURSAL INT,
    NOMBRE_SUCURSAL VARCHAR(200),
    COD_CIUDAD_SUCURSAL INT,
    CALLE_SUCURSAL VARCHAR(30),
    NRO_DIRECCION_SUCURSAL INT,
    PRIMARY KEY(COD_SUCURSAL),
    CONSTRAINT FOREIGN KEY(COD_CIUDAD_SUCURSAL) REFERENCES CIUDAD_SUCURSAL(COD_CIUDAD_SUCURSAL)
);

CREATE TABLE INVENTARIO(
    COD_INVENTARIO INT,
    COD_PRODUCTO INT,
    COD_SUCURSAL INT,
    CANTIDAD_TOTAL INT,
    CANTIDAD_DISPONIBLE INT,
    PRIMARY KEY(COD_INVENTARIO),
    CONSTRAINT FOREIGN KEY(COD_SUCURSAL) REFERENCES SUCURSAL(COD_SUCURSAL),
    CONSTRAINT FOREIGN KEY(COD_PRODUCTO) REFERENCES PRODUCTO(COD_PRODUCTO)
);

CREATE TABLE RESERVA(
    COD_RESERVA INT,
    CELULAR_CLIENTE INT,
    COD_DISPONIBILIDAD_FECHA INT,
    COD_VEHICULO INT,
    ESTADO INT,
    TOTAL INT,
    PRIMARY KEY(COD_RESERVA),
    CONSTRAINT FOREIGN KEY(CELULAR_CLIENTE) REFERENCES CLIENTE(CELULAR_CLIENTE),
    CONSTRAINT FOREIGN KEY(COD_DISPONIBILIDAD_FECHA) REFERENCES DISPONIBILIDAD_FECHA(COD_DISPONIBILIDAD_FECHA),
    CONSTRAINT FOREIGN KEY(COD_VEHICULO) REFERENCES VEHICULO(COD_VEHICULO)
    
);

CREATE TABLE PEDIDO(
    COD_PEDIDO INT,
    COD_PRODUCTO INT,
    COD_RESERVA INT,
    CANTIDAD_SOLICITADA INT,
    PRIMARY KEY(COD_PEDIDO),
    CONSTRAINT FOREIGN KEY (COD_PRODUCTO) REFERENCES PRODUCTO(COD_PRODUCTO),
    CONSTRAINT FOREIGN KEY(COD_RESERVA) REFERENCES RESERVA(COD_RESERVA)
);

CREATE TABLE HISTORIAL(
    COD_HISTORIAL INT,
    COD_RESERVA INT,
    FECHA_HISTORIAL DATE,
    PRIMARY KEY(COD_HISTORIAL),
    CONSTRAINT FOREIGN KEY(COD_RESERVA) REFERENCES RESERVA(COD_RESERVA)
    
);