DELIMITER //

CREATE TRIGGER vehiculo_auto_increment
BEFORE INSERT ON VEHICULO
FOR EACH ROW
BEGIN
    SET NEW.COD_VEHICULO = (SELECT COALESCE(MAX(COD_VEHICULO), 0) + 1 FROM VEHICULO);
END;

//

DELIMITER ;

DELIMITER //

CREATE TRIGGER rol_usuario_auto_increment
BEFORE INSERT ON ROL_USUARIO
FOR EACH ROW
BEGIN
    SET NEW.COD_ROL = (SELECT COALESCE(MAX(COD_ROL), 0) + 1 FROM ROL_USUARIO);
END;

//

DELIMITER ;

DELIMITER //

CREATE TRIGGER usuario_auto_increment
BEFORE INSERT ON USUARIO
FOR EACH ROW
BEGIN
    SET NEW.RUT_USUARIO = (SELECT COALESCE(MAX(RUT_USUARIO), 0) + 1 FROM USUARIO);
END;

//

DELIMITER ;

DELIMITER //

CREATE TRIGGER detalle_usuario_vehiculo_auto_increment
BEFORE INSERT ON DETALLE_USUARIO_VEHICULO
FOR EACH ROW
BEGIN
    SET NEW.COD_USUARIO_VEHICULO = (SELECT COALESCE(MAX(COD_USUARIO_VEHICULO), 0) + 1 FROM DETALLE_USUARIO_VEHICULO);
END;

//

DELIMITER ;

DELIMITER //

CREATE TRIGGER disponibilidad_fecha_auto_increment
BEFORE INSERT ON DISPONIBILIDAD_FECHA
FOR EACH ROW
BEGIN
    SET NEW.COD_DISPONIBILIDAD_FECHA = (SELECT COALESCE(MAX(COD_DISPONIBILIDAD_FECHA), 0) + 1 FROM DISPONIBILIDAD_FECHA);
END;

//

DELIMITER ;

DELIMITER //

CREATE TRIGGER cliente_auto_increment
BEFORE INSERT ON CLIENTE
FOR EACH ROW
BEGIN
    SET NEW.CELULAR_CLIENTE = (SELECT COALESCE(MAX(CELULAR_CLIENTE), 0) + 1 FROM CLIENTE);
END;

//

DELIMITER ;

DELIMITER //

CREATE TRIGGER producto_auto_increment
BEFORE INSERT ON PRODUCTO
FOR EACH ROW
BEGIN
    SET NEW.COD_PRODUCTO = (SELECT COALESCE(MAX(COD_PRODUCTO), 0) + 1 FROM PRODUCTO);
END;

//

DELIMITER ;

DELIMITER //

CREATE TRIGGER ciudad_sucursal_auto_increment
BEFORE INSERT ON CIUDAD_SUCURSAL
FOR EACH ROW
BEGIN
    SET NEW.COD_CIUDAD_SUCURSAL = (SELECT COALESCE(MAX(COD_CIUDAD_SUCURSAL), 0) + 1 FROM CIUDAD_SUCURSAL);
END;

//

DELIMITER ;

DELIMITER //

CREATE TRIGGER sucursal_auto_increment
BEFORE INSERT ON SUCURSAL
FOR EACH ROW
BEGIN
    SET NEW.COD_SUCURSAL = (SELECT COALESCE(MAX(COD_SUCURSAL), 0) + 1 FROM SUCURSAL);
END;

//

DELIMITER ;

DELIMITER //

CREATE TRIGGER inventario_auto_increment
BEFORE INSERT ON INVENTARIO
FOR EACH ROW
BEGIN
    SET NEW.COD_INVENTARIO = (SELECT COALESCE(MAX(COD_INVENTARIO), 0) + 1 FROM INVENTARIO);
END;

//

DELIMITER ;

DELIMITER //

CREATE TRIGGER reserva_auto_increment
BEFORE INSERT ON RESERVA
FOR EACH ROW
BEGIN
    SET NEW.COD_RESERVA = (SELECT COALESCE(MAX(COD_RESERVA), 0) + 1 FROM RESERVA);
END;

//

DELIMITER ;

DELIMITER //

CREATE TRIGGER pedido_auto_increment
BEFORE INSERT ON PEDIDO
FOR EACH ROW
BEGIN
    SET NEW.COD_PEDIDO = (SELECT COALESCE(MAX(COD_PEDIDO), 0) + 1 FROM PEDIDO);
END;

//

DELIMITER ;

DELIMITER //

CREATE TRIGGER historial_auto_increment
BEFORE INSERT ON HISTORIAL
FOR EACH ROW
BEGIN
    SET NEW.COD_HISTORIAL = (SELECT COALESCE(MAX(COD_HISTORIAL), 0) + 1 FROM HISTORIAL);
END;

//

DELIMITER ;